#ifndef FOC_OVERVIEW_TELEMETRY_H
#define FOC_OVERVIEW_TELEMETRY_H

/* Group 6 is numeric JustFloat for the VOFA dashboard. Groups 0..5 retain
 * their original 12-float frame and bit-packed acquisition headers. */
enum {
    TELEMETRY_SPEED_TARGET, TELEMETRY_SPEED_ACTUAL,
    TELEMETRY_POSITION_TARGET, TELEMETRY_POSITION_ACTUAL,
    TELEMETRY_IQ_TARGET, TELEMETRY_IQ_ACTUAL,
    TELEMETRY_ID_TARGET, TELEMETRY_ID_ACTUAL,
    TELEMETRY_BUS, TELEMETRY_UD, TELEMETRY_UQ,
    TELEMETRY_MODE, TELEMETRY_STATE, TELEMETRY_FAULT,
    TELEMETRY_WARNINGS, TELEMETRY_LAST_WARNING, TELEMETRY_REJECTED,
    TELEMETRY_VOLTAGE_SCALE, TELEMETRY_SPEED_REFERENCE,
    TELEMETRY_SPEED_ERROR, TELEMETRY_POSITION_ERROR, TELEMETRY_IQ_ERROR,
    TELEMETRY_TIME_US24, TELEMETRY_SEQUENCE24,
    TELEMETRY_OVERVIEW_CHANNELS
};
#define TELEMETRY_OVERVIEW_GROUP 6u
#define TELEMETRY_OVERVIEW_DECIMATION 2u /* Same byte budget as legacy frames. */
#endif
