#define foc foc0
#define FOC_GIMBAL_AXIS 0
#define foc_travel_deg foc0_travel_deg
#define foc_travel_ready foc0_travel_ready
#define foc_start_run foc0_start_run
#define foc_init foc0_init
#define foc_current foc0_current
#define foc_calibrate foc0_calibrate
#define foc_test foc0_test
#define foc_field_test foc0_field_test
#define foc_stop foc0_stop
#define foc_trip foc0_trip
#define foc_warn foc0_warn
#define foc_clear_warnings foc0_clear_warnings
#define foc_check foc0_check
#define foc_step foc0_step
#define foc_outer_step foc0_outer_step
#define foc_wrap foc0_wrap
#define foc_integrators foc0_integrators
#define foc_modulate foc0_modulate
#define foc_window foc0_window
#define control_torque control0_torque
#define control_test control0_test
#define control_target_valid control0_target_valid
#define control_speed control0_speed
#define control_position control0_position
#define control_hold_position control0_hold_position
#define control_zero control0_zero
#define control_stop control0_stop
#define control_resync control0_resync
#define control_step control0_step
#define control_fault control0_fault
#define control_scheduled control0_scheduled
#define control_mode control0_mode
#define control_iq_ref control0_iq_ref
#define control_speed_rpm control0_speed_rpm
#define control_speed_target control0_speed_target
#define control_speed_reference control0_speed_reference
#define control_position_deg control0_position_deg
#define control_position_target control0_position_target
#define motor_sample_us motor0_sample_us
