#define foc foc1
#define foc_init foc1_init
#define foc_current foc1_current
#define foc_calibrate foc1_calibrate
#define foc_test foc1_test
#define foc_stop foc1_stop
#define foc_trip foc1_trip
#define foc_warn foc1_warn
#define foc_clear_warnings foc1_clear_warnings
#define foc_check foc1_check
#define foc_step foc1_step
#define foc_outer_step foc1_outer_step
#define foc_wrap foc1_wrap
#define foc_integrators foc1_integrators
#define foc_modulate foc1_modulate
#define foc_window foc1_window
#define control_torque control1_torque
#define control_speed control1_speed
#define control_position control1_position
#define control_hold_position control1_hold_position
#define control_zero control1_zero
#define control_stop control1_stop
#define control_step control1_step
#define control_fault control1_fault
#define control_scheduled control1_scheduled
#define control_mode control1_mode
#define control_iq_ref control1_iq_ref
#define control_speed_rpm control1_speed_rpm
#define control_speed_target control1_speed_target
#define control_speed_reference control1_speed_reference
#define control_position_deg control1_position_deg
#define control_position_target control1_position_target
#define motor_sample_us motor1_sample_us
